CFLAGS          =
FFLAGS          =
CPPFLAGS        =
FPPFLAGS        =
LOCDIR          = src/makefile/examples/tests
EXAMPLESCPP     = ex1.cpp ex2.cpp ex3.cpp ex4.cpp
DIRS            =
CLEANFILES      =

include ${PETSCOPT_DIR}/lib/petscopt/conf/variables
include ${PETSCOPT_DIR}/lib/petscopt/conf/rules
include ${PETSCOPT_DIR}/lib/petscopt/conf/test
