CFLAGS          =
FFLAGS          =
CPPFLAGS        =
FPPFLAGS        =
LOCDIR          = src/tao/examples/tests
EXAMPLESC       =
EXAMPLESF       =
MANSEC          = Tao
DIRS            = petsc 
CLEANFILES      =

include ${PETSCOPT_DIR}/lib/petscopt/conf/variables
include ${PETSCOPT_DIR}/lib/petscopt/conf/rules
include ${PETSCOPT_DIR}/lib/petscopt/conf/test
