
ALL:

LOCDIR	 = src/tao/examples/
DIRS	 = tests
MANSEC   = Tao

include ${PETSCOPT_DIR}/lib/petscopt/conf/variables
include ${PETSCOPT_DIR}/lib/petscopt/conf/rules
include ${PETSCOPT_DIR}/lib/petscopt/conf/test
