
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = petscopt.c
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE  = libpetscopt
MANSEC   = Sys
LOCDIR   = src/sys

include ${PETSCOPT_DIR}/lib/petscopt/conf/variables
include ${PETSCOPT_DIR}/lib/petscopt/conf/rules
include ${PETSCOPT_DIR}/lib/petscopt/conf/test

