CFLAGS          =
FFLAGS          =
CPPFLAGS        =
FPPFLAGS        =
LOCDIR          = src/ts/examples/tests
EXAMPLESC       = ex1.c ex2.c ex3.c ex4.c ex5.c
EXAMPLESF       =
MANSEC          = TS
DIRS            = petsc 
CLEANFILES      =

include ${PETSCOPT_DIR}/lib/petscopt/conf/variables
include ${PETSCOPT_DIR}/lib/petscopt/conf/rules
include ${PETSCOPT_DIR}/lib/petscopt/conf/test
