
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = augmentedsnes.c
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE  = libpetscopt
MANSEC   = SNES
LOCDIR   = src/snes/

include ${PETSCOPT_DIR}/lib/petscopt/conf/variables
include ${PETSCOPT_DIR}/lib/petscopt/conf/rules
include ${PETSCOPT_DIR}/lib/petscopt/conf/test

