
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = augtriangular.c
SOURCEF  =
SOURCEH  =
DIRS     =
LIBBASE  = libpetscopt
MANSEC   = KSP
LOCDIR   = src/ksp/

include ${PETSCOPT_DIR}/lib/petscopt/conf/variables
include ${PETSCOPT_DIR}/lib/petscopt/conf/rules
include ${PETSCOPT_DIR}/lib/petscopt/conf/test

