
ALL:

LOCDIR	 = src/ts/examples/
DIRS	 = tests
MANSEC   = TS

include ${PETSCOPT_DIR}/lib/petscopt/conf/variables
include ${PETSCOPT_DIR}/lib/petscopt/conf/rules
include ${PETSCOPT_DIR}/lib/petscopt/conf/test
