
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = adjointts.c tlmts.c augmentedts.c tspropagator.c tssplitjac.c \
           tsgradhess.c tsobj.c tsopt.c tspdeconstrainedutils.c utils.c
SOURCEF  =
SOURCEH  =
DIRS     = examples
LIBBASE  = libpetscopt
MANSEC   = TS
LOCDIR   = src/ts/

include ${PETSCOPT_DIR}/lib/petscopt/conf/variables
include ${PETSCOPT_DIR}/lib/petscopt/conf/rules
include ${PETSCOPT_DIR}/lib/petscopt/conf/test

