
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = adjointts.c  tlmts.c  tsgradhess.c  tsobj.c  tspdeconstrainedutils.c  tspropagator.c  tssplitjac.c
SOURCEF  =
SOURCEH  =
DIRS     = examples
LIBBASE  = libpetscopt
MANSEC   = TS
LOCDIR   = src/ts/

include ${PETSCOPT_DIR}/lib/petscopt/conf/variables
include ${PETSCOPT_DIR}/lib/petscopt/conf/rules
include ${PETSCOPT_DIR}/lib/petscopt/conf/test

