
CFLAGS          =
FFLAGS          =
CPPFLAGS        =
FPPFLAGS        =
LOCDIR          = src/ts/examples/tests/petsc
EXAMPLESC       = ex16opt_p.c ex16opt_ic.c ex20opt_p.c
EXAMPLESF       =
MANSEC          = TS
DIRS            = advection-diffusion-reaction
CLEANFILES      =

include ${PETSCOPT_DIR}/lib/petscopt/conf/variables
include ${PETSCOPT_DIR}/lib/petscopt/conf/rules
include ${PETSCOPT_DIR}/lib/petscopt/conf/test
