
CFLAGS          =
FFLAGS          =
CPPFLAGS        =
FPPFLAGS        =
LOCDIR          = src/ts/examples/tests/petsc/advection-diffusion-reaction
EXAMPLESC       = ex5adj.c
EXAMPLESF       =
MANSEC          = TS
DIRS            =
CLEANFILES      =

include ${PETSCOPT_DIR}/lib/petscopt/conf/variables
include ${PETSCOPT_DIR}/lib/petscopt/conf/rules
include ${PETSCOPT_DIR}/lib/petscopt/conf/test
